version: '2'
services:
  mysql:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: iot
      MYSQL_DATABASE: iot
      MYSQL_USER: iot
      MYSQL_PASSWORD: iot
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: –smallfiles